
name: Build and test 

on:
  workflow_dispatch: #This would normally be a merge trigger

  workflow_call: 
    inputs:
      publish-artifact:
        type: boolean

env:
  PROJECT_DIR: ./src/console

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'
      
      - name: Build
        working-directory: '${{env.PROJECT_DIR}}'
        run: |
          dotnet build console.csproj --configuration Release -o out
          ls
        
      - name: Upload artifacts
        if: ${{inputs.publish-artifact}}
        uses: actions/upload-artifact@v3
        with:
          name: console-app
          path: ${{env.PROJECT_DIR}}/out

          