
name: Build and test LeanIX Function App solution

on:
  workflow_call: 

env:
  PROJECT_DIR: ./src/console

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'
      
      - name: Build
        working-directory: '${{env.PROJECT_DIR}}'
        run: |
          dotnet build --configuration Release -o ${{env.PROJECT_DIR}}/out
          ls ${{env.PROJECT_DIR}}

      - name: Zip
        run: zip ${{env.PROJECT_DIR}}/out.zip ${{env.PROJECT_DIR}}/out -r
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: console-app
          path: ${{env.PROJECT_DIR}}/out.zip