
name: Build and test 

on:
  workflow_dispatch: #This would normally be a merge trigger

  workflow_call:

env:
  PROJECT_DIR: ./src/console

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'
      
      - name: Build
        run: dotnet build ${{env.PROJECT_DIR}}/console.csproj --configuration Release -o out
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: console-app
          path: ./out

          