
name: Build and test 

on:
  workflow_dispatch: #This would normally be a merge trigger

  workflow_call: 
    inputs:
      environment:
        type: string
        required: true

env:
  PROJECT_DIR: ./src/console

jobs:
  tfplan:
    name: tfplan-${{inputs.environment}}
    runs-on: ubuntu-latest
    steps:
      - name: Plan
        run: echo "Executing pre-plan"

          